# Simple(ish) workflow for deploying static content to GitHub Pages
name: CI

on:
  # Runs on pushes targeting the default branch
  push:
    branches:
      - master
  # Runs on PRs
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - master

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    name: Typecheck and Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0
        with:
          submodules: true
      - uses: actions/setup-node@v3.5.1
        with:
          node-version: "16"
          cache: "npm"
      - name: Cache node_modules
        id: cache-node_modules
        uses: actions/cache@v3.2.1
        with:
          path: node_modules
          key: node_modules-${{ hashFiles('package.json', 'package-lock.json') }}
      # Install npm packages, unless we restored them from cache.
      # Since `npm ci` removes the node_modules folder before running it’s
      # important to skip this step if cache was restored.
      # `npm ci` does two things:
      # 1. Installs everything in package-lock.json.
      # 2. Checks that package.json and package-lock.json are in sync.
      # That’s why the cache depends on both package-lock.json and package.json.
      - name: Install npm dependencies
        if: steps.cache-node_modules.outputs.cache-hit != 'true'
        run: npm ci
      - name: Build
        run: npm run build
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1.0.7
        with:
          path: "./dist/"
          name: build-directory
  test:
    name: Vitest and Coverage
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0
        with:
          submodules: true
      - uses: actions/setup-node@v3.5.1
        with:
          node-version: "16"
          cache: "npm"
      - name: Cache node_modules
        id: cache-node_modules
        uses: actions/cache@v3.2.1
        with:
          path: node_modules
          key: node_modules-${{ hashFiles('package.json', 'package-lock.json') }}
      # Install npm packages, unless we restored them from cache.
      # Since `npm ci` removes the node_modules folder before running it’s
      # important to skip this step if cache was restored.
      # `npm ci` does two things:
      # 1. Installs everything in package-lock.json.
      # 2. Checks that package.json and package-lock.json are in sync.
      # That’s why the cache depends on both package-lock.json and package.json.
      - name: Install npm dependencies
        if: steps.cache-node_modules.outputs.cache-hit != 'true'
        run: npm ci
      - name: Test
        run: "npm run test:no-watch"
      - name: Coverage
        if: always() # Also generate the report if tests are failing
        run: npx vitest --coverage
      - name: "Report Coverage"
        uses: davelosert/vitest-coverage-report-action@v1.3.1

  lint:
    name: Linting
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0
        with:
          submodules: true
      - uses: actions/setup-node@v3.5.1
        with:
          node-version: "16"
          cache: "npm"
      - name: Cache node_modules
        id: cache-node_modules
        uses: actions/cache@v3.2.1
        with:
          path: node_modules
          key: node_modules-${{ hashFiles('package.json', 'package-lock.json') }}
      # Install npm packages, unless we restored them from cache.
      # Since `npm ci` removes the node_modules folder before running it’s
      # important to skip this step if cache was restored.
      # `npm ci` does two things:
      # 1. Installs everything in package-lock.json.
      # 2. Checks that package.json and package-lock.json are in sync.
      # That’s why the cache depends on both package-lock.json and package.json.
      - name: Install npm dependencies
        if: steps.cache-node_modules.outputs.cache-hit != 'true'
        run: npm ci
      - name: Link Check
        if: ${{ always() }}
        uses: gaurav-nelson/github-action-markdown-link-check@v1
        with:
          use-quiet-mode: false
          use-verbose-mode: false
          config-file: mlc_config.json
          folder-path: "docs"
          file-path: "./README.md, ./CONTRIBUTORS.md"
          max-depth: -1
          check-modified-files-only: false
          base-branch: master
          file-extension: ".md"
      - name: Markdownlint
        if: ${{ always() }}
        uses: DavidAnson/markdownlint-cli2-action@v9.0.0
      - name: Spell Check
        uses: streetsidesoftware/cspell-action@v2.15.1

  lhci:
    name: Lighthouse CI
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0
        with:
          submodules: true
      - uses: actions/download-artifact@v3.0.2
        with:
          # Artifact name
          name: build-directory
          # Destination path
          path: "./dist/"
      - name: Audit URLs using Lighthouse
        uses: treosh/lighthouse-ci-action@v9
        with:
          configPath: "./lighthouserc.json"
          budgetPath: ./budget.json # test performance budgets
          uploadArtifacts: true # save results as an action artifacts
          temporaryPublicStorage: true # upload lighthouse report to the temporary storage
          runs: 3

  deploy:
    name: Deploy static content to Pages
    needs: [build, lint, test, lhci]
    if: ${{ github.ref_name == 'master' }}
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }} # TODO: switch this (actions/deploy-pages#73)

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0
      - name: Setup Pages
        uses: actions/configure-pages@v3.0.2
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1.2.4
